name: hello-cicd
on: push

jobs:
  ci:
    name: build and test
    runs-on: ubuntu-latest
    steps:
    - name: Descargar fuentes
      uses: actions/checkout@v2
    - name: Configurar JDK 1.11
      uses: actions/setup-java@v1
      with:
          java-version: 1.11
    - name: compilar con maven
      run: mvn -B package --file pom.xml
    - name: subir binarios
      uses: actions/upload-artifact@v2
      with:
        name: hello-artifact
        path: |
          target/*.jar
          target/lib/
          src/main/docker/Dockerfile.jvm
  cd:
    name: package and distribute
    runs-on: ubuntu-latest
    needs: ci
    steps:
    - name: descargar compilados
      uses: actions/download-artifact@v2
      with:
        name: hello-artifact
    - name: deplegar al registro
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: src/main/docker/Dockerfile.jvm
        repository: ${{ github.repository }}
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}