name: hello-cicd
on: push

jobs:
  build:
    name: build jar
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Configurar JDK 1.11
      uses: actions/setup-java@v1
      with:
          java-version: 1.11
    - name: compilar con maven
      run: mvn -B package --file pom.xml
    - uses: docker/build-push-action@v1
      name: deplegar al registro
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: src/main/docker/Dockerfile.fast-jar
        repository: ${{ github.repository }}
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}