on: push
name: deploy
jobs:
  build:
    name: build jar
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
          java-version: 1.8
    - name: Build with Maven
      run: mvn package --file pom.xml
  deploy:
    name: deploy to registry
    runs-on: ubuntu-latest
    steps:
    - uses: docker/build-push-action@v1
    - name: push to docker
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: src/main/docker/Dockerfile.fast-jar
        repository: ${{ github.repository }}
        tag_with_ref: true
        tag_with_sha: true
        tags: ${{ github.sha }}